### ISSUE TITLE
Issue when i define board as 35

### ISSUE THREAD

**Issue by shadinew** [Polar3D/Polar-3D-Firmware#6]
The issue when i change the board type from 85 to 35 the following error appearing 
![Error](https://user-images.githubusercontent.com/34856544/89061796-66a65580-d376-11ea-81e6-c77169b793db.gif)

then i change the #include Wprogram.h to Arduino.h another error came up as follows.

![Error2](https://user-images.githubusercontent.com/34856544/89062635-dcf78780-d377-11ea-8f45-e6ef4c05529a.jpg)

**Comment by wjsteele** [comment]
This is actually not an issue with the firmware, it's because you're using the 1.x version of the Arduino environment.  These breaking changes were documented in the Arduino forums long ago... have a look at their changes and you'll understand it.  Optionally, you can download the old Arduino 022 that this was built on.

**Comment by shadinew** [comment]
I will check Thanks for the help

**Comment by shadinew** [comment]
Hi I have used the version you recommended to use however Error again showed up, sorry to say might be something easy however my programming
![Error3](https://user-images.githubusercontent.com/34856544/89079419-7a15e880-d397-11ea-8697-5228b2378041.png)
 knowledge is not good at all so excuse my stupidity :)

**Comment by wjsteele** [comment]
What kind of machine are you trying to run this on?  Is there a reason the mainline version of Marlin can't be used? This particular version is specific to the old Polar 3D printer and no effort was ever made to support other printers.BillOn Jul 31, 2020 5:37 PM, shadinew <notifications@github.com> wrote:
Hi I have used the version you recommended to use however Error again showed up, sorry to say might be something easy however my programming

knowledge is not good at all so excuse my stupidity :)

**Comment by shadinew** [comment]
I have designed my own polar 3D printer and i used the the Marlin R-360 that meant to be used for R-360 machine however i guess the R-360 is not working as when i enable # define R-360 the machine is not behaving as it should be however it works as Cartesian however it lacks of accuracy which requires to enable R-360 i have posted the machine design and pic on these links https://reprap.org/forum/read.php?185,874711,875634#msg-875634 so i thought using other version could run it. 
Electronics used are Arduino Mega with shield Ramps 1.4
